- name: Claude Code Action Official
  uses: anthropics/claude-code-action@v1
  with:
    trigger_phrase: "@claude"  # 선택 사항, 기본값은 @claude
    assignee_trigger: ""       # 선택 사항
    label_trigger: "claude"    # 선택 사항, 기본값은 claude
    base_branch: ""            # 선택 사항
    branch_prefix: "claude/"   # 선택 사항, 기본값은 claude/
    model: ""                  # 선택 사항
    anthropic_model: ""        # 선택 사항
    fallback_model: ""         # 선택 사항
    allowed_tools: []          # 선택 사항, 기본값은 []
    disallowed_tools: []       # 선택 사항, 기본값은 []
    custom_instructions: ""    # 선택 사항
    direct_prompt: ""          # 선택 사항
    mcp_config: "{}"           # 선택 사항
    additional_permissions: "" # 선택 사항, 기본값은 ""
    claude_env: ""             # 선택 사항, 기본값은 ""
    anthropic_api_key: ""      # 선택 사항
    claude_code_oauth_token: ""# 선택 사항
    github_token: ""           # 선택 사항
    use_bedrock: false         # 선택 사항, 기본값은 false
    use_vertex: false          # 선택 사항, 기본값은 false
    max_turns: ""              # 선택 사항
    timeout_minutes: 30        # 선택 사항, 기본값은 30
    use_sticky_comment: false  # 선택 사항, 기본값은 false
    use_commit_signing: false  # 선택 사항, 기본값은 false
